name: flutter_test_aplication
description: "delivery app"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/resources/imgs/logo_img.png
    - lib/resources/imgs/error_not_found.jpg
    - lib/resources/imgs/border_pizza.jpg
  fonts:
    - family: SageWold
      fonts:
        - asset: lib/resources/theme/fonts/Sagewold-Regular.otf
        - asset: lib/resources/theme/fonts/Sagewold-Italic.otf
          style: italic